name: test_dug

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: push

jobs:

  test-dug:
    name: dug-test-mpi
    runs-on: [self-hosted, dug-mpi]

    env:

      # Devito setup
      DEVITO_LANGUAGE: "openmp"
      DEVITO_ARCH: "gcc-9"
      DEVITO_BACKEND: "core"
      CC: "gcc-9"
      CXX: "g++-9"

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Run DUG test
      uses: fifsky/ssh-action@master
      with:
        command: |
          ssh ${{ secrets.DUG_LOGIN }}@pgpu0001 << EOF
            cd devito
            git fetch
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git pull
            chmod a+x .github/scripts/ci_mpi.sh
            .github/scripts/ci_mpi.sh
          EOF
        host: ${{ secrets.DUG_HNODE }}
        port: ${{ secrets.DUG_PORT }}
        user: ${{ secrets.DUG_LOGIN }}
        pass: ${{ secrets.DUG_PASSWORD }}
        args: "-tt"
