# Runner informaiton:
# Standard F4s_v2 (4 vcpus, 8 GiB memory)
# Intel Xeon® Platinum 8168 (SkyLake)

name: CI-mpi

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: pytest-mpi
    runs-on: self-hosted

    env:
      DEVITO_ARCH: "gcc-7"
      DEVITO_LANGUAGE: "openmp"
      DEVITO_BACKEND: "core"
      CC: "gcc-7"
      CXX: "g++-7"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -e .[extras]

    - name: Test with pytest
      run: |
        pytest --cov --cov-config=.coveragerc --cov-report=xml -m parallel tests/

    - name: Test notebooks
      run : |
        # Currently not tested due to issue #859
        # ipcluster start --profile=mpi -n 4 --daemon
        # py.test --nbval examples/mpi
        # ipcluster stop --profile=mpi

    - name: Test seismic examples
      run: |
        DEVITO_MPI=1 mpirun -n 4 py.test examples/seismic/tti/tti_example.py
        DEVITO_MPI=1 mpirun -n 4 py.test examples/seismic/elastic/elastic_example.py
        DEVITO_MPI=1 mpirun -n 4 py.test examples/seismic/viscoacoustic/viscoacoustic_example.py
        DEVITO_MPI=1 mpirun -n 4 py.test examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test fwi examples
      run: |
        DEVITO_MPI=1 mpirun -n 4 python examples/seismic/inversion/fwi.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: pytest-mpi
