name: CI-london

on: push

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: [self-hosted, X64, macOS]

    env:
      DEVITO_ARCH: "${{ matrix.arch }}"
      DEVITO_LANGUAGE: ${{ matrix.language }}
      DEVITO_BACKEND: "core"
      OMP_NUM_THREADS: 2
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           pytest-osx-py37-clang-omp
        ]
        include:
        - name: pytest-osx-py37-clang-omp
          python-version: 3.7
          os: macos-latest
          arch: "osx"
          language: "C"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.name != 'pytest-docker-py36-gcc-omp'
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build docker image
      if: matrix.name == 'pytest-docker-py36-gcc-omp'
      run: |
          docker build . --file docker/Dockerfile --tag devito_img
          echo "::set-env name=RUN_CMD::docker run --rm --name testrun devito_img"

    - name: Install GCC ${{ matrix.arch }}
      if: runner.os == 'linux'
      run : |
        sudo apt-get install -y ${{ matrix.arch }}

    - name: Reduce number of tests for OSX
      if: runner.os == 'macOS'
      run : |
        echo "::set-env name=TESTS::tests/test_operator.py"

    - name: Install dependencies
      if: matrix.name != 'pytest-docker-py36-gcc-omp'
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Test with pytest
      run: |
        $RUN_CMD pytest -m "not parallel" --cov --cov-config=.coveragerc --cov-report=xml $TESTS

    #- name: Upload coverage to Codecov
      #if: matrix.name != 'pytest-docker-py36-gcc-omp'
      #uses: codecov/codecov-action@v1.0.6
      #with:
        #token: ${{ secrets.CODECOV_TOKEN }}
        #name: ${{ matrix.name }}
