# Runner information:
# pytest-gpu-omp:
# CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
# GPU: NVIDIA GeForce GTX 960
# pytest-gpu-acc:
# CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
# GPU: NVIDIA GeForce RTX 2060

name: CI-gpu

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.tags }}

    env:
      OMPI_CC: ${{ matrix.arch }}

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
          pytest-gpu-omp,
          pytest-gpu-acc
        ]
        include:
        - name: pytest-gpu-omp
          test_file: "tests/test_gpu_openmp.py"
          arch: "clang"
          platform: "nvidiaX"
          language: "openmp"
          tags: ["self-hosted", "gpu", "openmp"]

        - name: pytest-gpu-acc
          test_file: "tests/test_gpu_openacc.py"
          arch: "nvc"
          platform: "nvidiaX"
          language: "openacc"
          tags: ["self-hosted", "gpu", "openacc"]

    steps:
    - name: Checkout devito
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # NOTE: Using 'source' during every step is ugly and should be changed
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pip install --upgrade pip
        pip install -e .[extras]

    - name: Test with pytest
      run: |
        nvidia-smi
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pytest --cov --cov-config=.coveragerc --cov-report=xml ${{ matrix.test_file }}

    - name: Test examples
      run: |
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pytest examples/seismic/acoustic/acoustic_example.py
        pytest examples/seismic/elastic/elastic_example.py
        pytest examples/seismic/tti/tti_example.py
        pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test examples with MPI
      run: |
        # Tests currently being executed individually due to issue #1536
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT2-1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT2-2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT2-3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT4-1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT4-2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic_stability[OT4-3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic[True-369.955-float32]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py::test_isoacoustic[False-459.1678-float64]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py::test_elastic[float32]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py::test_elastic[float64]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py::examples/seismic/elastic/elastic_example.py::test_elastic_stability[1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py::examples/seismic/elastic/elastic_example.py::test_elastic_stability[2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py::examples/seismic/elastic/elastic_example.py::test_elastic_stability[3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py::test_tti_stability[2-centered]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py::test_tti_stability[2-staggered]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py::test_tti_stability[3-centered]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py::test_tti_stability[3-staggered]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic[float32]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic[float64]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[blanch_symes-1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[blanch_symes-2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[blanch_symes-3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[ren-1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[ren-2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[ren-3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[deng_mcmechan-1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[deng_mcmechan-2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py::test_viscoacoustic_stability[deng_mcmechan-3]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py::test_viscoelastic[float32]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py::test_viscoelastic[float64]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py::test_viscoelastic_stability[1]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py::test_viscoelastic_stability[2]
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py::test_viscoelastic_stability[3]

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ${{ matrix.name }}
