# Runner information:
# pytest-gpu-omp:
# CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
# GPU: NVIDIA GeForce GTX 960
# pytest-gpu-acc:
# CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
# GPU: NVIDIA GeForce RTX 2060

name: CI-gpu

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.tags }}

    env:
      OMPI_CC: ${{ matrix.arch }}

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
          pytest-gpu-omp,
          pytest-gpu-acc
        ]
        include:
        - name: pytest-gpu-omp
          test_file: "tests/test_gpu_openmp.py"
          arch: "clang"
          platform: "nvidiaX"
          language: "openmp"
          tags: ["self-hosted", "rhodrin"]

        - name: pytest-gpu-acc
          test_file: "tests/test_gpu_openacc.py"
          arch: "nvcc"
          platform: "nvidiaX"
          language: "openacc"
          tags: ["self-hosted", "gerard"]

    steps:
    - name: Checkout devito
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # NOTE: Using 'source' during every step is ugly and should be changed
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pip install --upgrade pip
        pip install -e .[extras]

    - name: Test with pytest
      run: |
        nvidia-smi
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pytest --cov --cov-config=.coveragerc --cov-report=xml ${{ matrix.test_file }}

    - name: Test examples
      run: |
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        pytest examples/seismic/acoustic/acoustic_example.py
        pytest examples/seismic/elastic/elastic_example.py
        pytest examples/seismic/tti/tti_example.py
        pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test examples with MPI
      # Skip openmp for now due to issue #1536
      if: matrix.name != 'pytest-gpu-acc'
      run: |
        source ~/environments/${{ matrix.language }}/bin/activate
        source ~/environments/scripts/${{ matrix.language }}_env.sh
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ${{ matrix.name }}
